isc.Tree.create({
    ID:"docTree",
    root:{
        name:"/",
        children:[
            {contentsURL:"[docRoot]SmartClient_Quick_Start_Guide.pdf", icon:"[SKIN]pdf.gif", 
             id:"QuickStartGuide",title:"SmartClient QuickStart Guide"},
            {contentsURL:"[referenceRoot]SmartClient_Explorer.html", icon:"[SKIN]features.png", 
             id:"FeatureExplorer",title:"Feature Explorer"},
            {icon:"[SKIN]cube_blue.gif", ref:"group:featureExplorerOverview", 
             id:"featureExplorerOverview",title:"Feature Explorer Overview"},
            {
                isOpen:"true",
                title:"Concepts",
                children:[
                    {
                        title:"Client-Server Integration",
                        id:"2",
                        children:[
                            {id:"41", ref:"group:clientDataIntegration", icon:"[SKIN]cube_blue.gif", 
                             title:"Client-side Data Integration"},
                            {id:"56", ref:"group:serverDataIntegration", icon:"[SKIN]cube_blue.gif", 
                             title:"Server DataSource Integration"}
                        ],
                        icon:"[SKIN]cube_blue.gif",
                        ref:"group:clientServerIntegration"
                    },
                    {title:"SmartClient Architecture", id:"3", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:smartArchitecture"},
                    {title:"Debugging", id:"4", icon:"[SKIN]cube_blue.gif", ref:"group:debugging"},
                    {title:"Deploying SmartClient", id:"5", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:iscInstall"},
                    {title:"Visual Builder", id:"6", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:visualBuilder"},
                    {title:".NET, PHP, Serverless Integration", id:"7", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:nonJavaBackend"},
                    {title:"Integration with Spring", id:"8", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:springIntegration"},
                    {title:"Integration with Hibernate", id:"9", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:hibernateIntegration"},
                    {title:"Integration with JSF", id:"10", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:jsfIntegration"},
                    {title:"Integration with Struts", id:"11", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:strutsIntegration"},
                    {
                        title:"Component XML",
                        id:"12",
                        icon:"[SKIN]cube_blue.gif",
                        ref:"group:componentXML",
                        children:[
                            {id:"34", ref:"group:componentSchema", icon:"[SKIN]cube_blue.gif", 
                             title:"Component Schema"}
                        ]
                    },
                    {id:"37", ref:"group:i18n", icon:"[SKIN]cube_blue.gif", 
                     title:"Internationalization and Localization (i18n,l10n)"},
                    {id:"64", ref:"group:skinning", icon:"[SKIN]cube_blue.gif", 
                     title:"Skinning / Theming"}
                ],
                id:"0"
            },
            {
                isOpen:"true",
                title:"Client Reference",
                children:[
                    {
                        title:"Grids",
                        isFolder:true,
                        id:"13",
                        children:[
                            {
                                id:"69",
                                ref:"class:TreeGrid",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"TreeGrid",
                                children:[
                                    {id:"70", ref:"object:TreeNode", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"TreeNode"},
                                    {id:"81", ref:"object:TreeGridField", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"TreeGridField"}
                                ]
                            },
                            {
                                id:"73",
                                ref:"class:DetailViewer",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"DetailViewer",
                                children:[
                                    {id:"74", ref:"object:DetailViewerRecord", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"DetailViewerRecord"},
                                    {id:"75", ref:"object:DetailViewerField", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"DetailViewerField"}
                                ]
                            },
                            {
                                id:"77",
                                ref:"class:ListGrid",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"ListGrid",
                                children:[
                                    {id:"78", ref:"object:ListGridRecord", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ListGridRecord"},
                                    {id:"79", ref:"object:groupNode", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"groupNode"},
                                    {id:"80", ref:"object:ListGridField", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ListGridField"}
                                ]
                            },
                            {id:"85", ref:"class:DOMGrid", icon:"[SKIN]text_code_javascript.gif", 
                             title:"DOMGrid"}
                        ]
                    },
                    {
                        title:"Forms",
                        isFolder:true,
                        id:"14",
                        children:[
                            {id:"30", ref:"group:formLayout", icon:"[SKIN]cube_blue.gif", 
                             title:"Form Layout"},
                            {
                                id:"31",
                                title:"Form Items",
                                children:[
                                    {
                                        id:"32",
                                        ref:"class:FileItem",
                                        icon:"[SKIN]text_code_javascript.gif",
                                        title:"FileItem",
                                        children:[
                                            {id:"33", ref:"group:upload", icon:"[SKIN]cube_blue.gif", 
                                             title:"Uploading Files"}
                                        ]
                                    },
                                    {
                                        id:"91",
                                        ref:"class:FormItem",
                                        icon:"[SKIN]text_code_javascript.gif",
                                        title:"FormItem",
                                        children:[
                                            {id:"92", ref:"object:FormItemIcon", 
                                             icon:"[SKIN]text_code_javascript.gif",title:"FormItemIcon"}
                                        ]
                                    },
                                    {id:"95", ref:"class:CanvasItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"CanvasItem"},
                                    {id:"96", ref:"class:TextItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"TextItem"},
                                    {id:"97", ref:"class:BlurbItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"BlurbItem"},
                                    {id:"98", ref:"class:ButtonItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ButtonItem"},
                                    {id:"99", ref:"interface:PickList", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"PickList"},
                                    {id:"100", ref:"class:SelectItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SelectItem"},
                                    {id:"101", ref:"class:SelectOtherItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SelectOtherItem"},
                                    {id:"102", ref:"class:CheckboxItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"CheckboxItem"},
                                    {id:"103", ref:"class:NativeCheckboxItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"NativeCheckboxItem"},
                                    {id:"104", ref:"class:HeaderItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"HeaderItem"},
                                    {id:"105", ref:"class:SectionItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SectionItem"},
                                    {id:"106", ref:"class:HiddenItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"HiddenItem"},
                                    {id:"107", ref:"class:StaticTextItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"StaticTextItem"},
                                    {id:"108", ref:"class:LinkItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"LinkItem"},
                                    {id:"109", ref:"class:PasswordItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"PasswordItem"},
                                    {id:"110", ref:"class:RadioGroupItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"RadioGroupItem"},
                                    {id:"111", ref:"class:ResetItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ResetItem"},
                                    {id:"112", ref:"class:DateItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"DateItem"},
                                    {id:"113", ref:"class:SpacerItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SpacerItem"},
                                    {id:"114", ref:"class:RowSpacerItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"RowSpacerItem"},
                                    {id:"115", ref:"class:SubmitItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SubmitItem"},
                                    {id:"116", ref:"class:TextAreaItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"TextAreaItem"},
                                    {id:"117", ref:"class:TimeItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"TimeItem"},
                                    {id:"118", ref:"class:ToolbarItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ToolbarItem"},
                                    {id:"119", ref:"class:UploadItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"UploadItem"},
                                    {id:"120", ref:"class:ComboBoxItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ComboBoxItem"},
                                    {
                                        id:"121",
                                        ref:"class:MultiFileItem",
                                        icon:"[SKIN]text_code_javascript.gif",
                                        title:"MultiFileItem",
                                        children:[
                                            {id:"122", ref:"class:MultiFilePicker", 
                                             icon:"[SKIN]text_code_javascript.gif",title:"MultiFilePicker"}
                                        ]
                                    },
                                    {id:"123", ref:"class:SpinnerItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SpinnerItem"},
                                    {id:"124", ref:"class:SliderItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SliderItem"},
                                    {id:"125", ref:"class:PickTreeItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"PickTreeItem"},
                                    {id:"129", ref:"class:RichTextItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"RichTextItem"}
                                ]
                            },
                            {id:"88", ref:"class:DateChooser", icon:"[SKIN]text_code_javascript.gif", 
                             title:"DateChooser"},
                            {id:"90", ref:"class:DynamicForm", icon:"[SKIN]text_code_javascript.gif", 
                             title:"DynamicForm"},
                            {
                                id:"93",
                                ref:"class:Validator",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Validator",
                                children:[
                                    {id:"94", ref:"class:ValidatorTypes", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ValidatorTypes"}
                                ]
                            },
                            {id:"126", ref:"class:SearchForm", icon:"[SKIN]text_code_javascript.gif", 
                             title:"SearchForm"},
                            {id:"127", ref:"class:ValuesManager", 
                             icon:"[SKIN]text_code_javascript.gif",title:"ValuesManager"},
                            {id:"157", ref:"class:PropertySheet", 
                             icon:"[SKIN]text_code_javascript.gif",title:"PropertySheet"}
                        ]
                    },
                    {
                        title:"Layout",
                        isFolder:true,
                        id:"15",
                        children:[
                            {id:"171", ref:"class:Layout", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Layout"},
                            {id:"172", ref:"class:HLayout", icon:"[SKIN]text_code_javascript.gif", 
                             title:"HLayout"},
                            {id:"173", ref:"class:VLayout", icon:"[SKIN]text_code_javascript.gif", 
                             title:"VLayout"},
                            {id:"174", ref:"class:HStack", icon:"[SKIN]text_code_javascript.gif", 
                             title:"HStack"},
                            {id:"175", ref:"class:VStack", icon:"[SKIN]text_code_javascript.gif", 
                             title:"VStack"},
                            {id:"176", ref:"class:LayoutSpacer", icon:"[SKIN]text_code_javascript.gif", 
                             title:"LayoutSpacer"},
                            {id:"184", ref:"class:Toolbar", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Toolbar"},
                            {
                                id:"185",
                                ref:"class:ToolStrip",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"ToolStrip",
                                children:[
                                    {id:"186", ref:"class:ToolStripSeparator", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ToolStripSeparator"},
                                    {id:"197", ref:"class:ToolStripResizer", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ToolStripResizer"}
                                ]
                            },
                            {
                                id:"189",
                                ref:"class:SectionStack",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"SectionStack",
                                children:[
                                    {id:"190", ref:"object:SectionStackSection", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SectionStackSection"},
                                    {id:"191", ref:"class:SectionHeader", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SectionHeader"},
                                    {id:"192", ref:"class:ImgSectionHeader", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ImgSectionHeader"}
                                ]
                            },
                            {id:"194", ref:"class:Splitbar", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Splitbar"},
                            {id:"195", ref:"class:ImgSplitbar", icon:"[SKIN]text_code_javascript.gif", 
                             title:"ImgSplitbar"},
                            {id:"196", ref:"class:Snapbar", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Snapbar"},
                            {
                                id:"218",
                                ref:"class:TabSet",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"TabSet",
                                children:[
                                    {id:"219", ref:"class:TabBar", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"TabBar"},
                                    {id:"222", ref:"object:Tab", icon:"[SKIN]text_code_javascript.gif", 
                                     title:"Tab"}
                                ]
                            },
                            {id:"220", ref:"class:Window", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Window"}
                        ]
                    },
                    {
                        title:"Control",
                        isFolder:true,
                        id:"16",
                        children:[
                            {id:"66", ref:"group:Prompting", icon:"[SKIN]cube_blue.gif", 
                             title:"Prompting"},
                            {
                                id:"82",
                                ref:"class:Menu",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Menu",
                                children:[
                                    {id:"83", ref:"object:MenuItem", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"MenuItem"}
                                ]
                            },
                            {id:"84", ref:"class:MenuButton", icon:"[SKIN]text_code_javascript.gif", 
                             title:"MenuButton"},
                            {id:"86", ref:"class:MenuBar", icon:"[SKIN]text_code_javascript.gif", 
                             title:"MenuBar"},
                            {id:"89", ref:"class:Slider", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Slider"},
                            {
                                id:"177",
                                ref:"class:Button",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Button",
                                children:[
                                    {id:"178", ref:"class:AutoFitButton", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"AutoFitButton"}
                                ]
                            },
                            {id:"179", ref:"class:IButton", icon:"[SKIN]text_code_javascript.gif", 
                             title:"IButton"},
                            {id:"183", ref:"class:Progressbar", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Progressbar"},
                            {id:"187", ref:"class:ImgButton", icon:"[SKIN]text_code_javascript.gif", 
                             title:"ImgButton"},
                            {id:"188", ref:"class:StretchImgButton", 
                             icon:"[SKIN]text_code_javascript.gif",title:"StretchImgButton"},
                            {id:"216", ref:"class:Hover", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Hover"},
                            {id:"221", ref:"class:Dialog", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Dialog"}
                        ]
                    },
                    {
                        title:"Foundation",
                        isFolder:true,
                        id:"17",
                        children:[
                            {id:"76", ref:"class:GridRenderer", icon:"[SKIN]text_code_javascript.gif", 
                             title:"GridRenderer"},
                            {id:"128", ref:"class:RichTextEditor", 
                             icon:"[SKIN]text_code_javascript.gif",title:"RichTextEditor"},
                            {id:"138", ref:"object:Browser", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Browser"},
                            {id:"158", ref:"class:ViewLoader", icon:"[SKIN]text_code_javascript.gif", 
                             title:"ViewLoader"},
                            {id:"159", ref:"class:HTMLFlow", icon:"[SKIN]text_code_javascript.gif", 
                             title:"HTMLFlow"},
                            {id:"160", ref:"class:HTMLPane", icon:"[SKIN]text_code_javascript.gif", 
                             title:"HTMLPane"},
                            {id:"170", ref:"class:StatefulCanvas", 
                             icon:"[SKIN]text_code_javascript.gif",title:"StatefulCanvas"},
                            {id:"180", ref:"class:Img", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Img"},
                            {id:"181", ref:"class:StretchImg", icon:"[SKIN]text_code_javascript.gif", 
                             title:"StretchImg"},
                            {id:"182", ref:"class:Label", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Label"},
                            {id:"193", ref:"class:Scrollbar", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Scrollbar"},
                            {
                                id:"212",
                                ref:"class:Canvas",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Canvas",
                                children:[
                                    {id:"213", ref:"object:ImgProperties", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"ImgProperties"}
                                ]
                            },
                            {id:"215", ref:"class:EdgedCanvas", icon:"[SKIN]text_code_javascript.gif", 
                             title:"EdgedCanvas"},
                            {id:"217", ref:"class:ImgTab", icon:"[SKIN]text_code_javascript.gif", 
                             title:"ImgTab"}
                        ]
                    },
                    {
                        title:"Data Binding",
                        isFolder:true,
                        id:"18",
                        children:[
                            {
                                id:"35",
                                ref:"class:DataSource",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"DataSource",
                                children:[
                                    {id:"36", ref:"group:dataSourceDeclaration", 
                                     icon:"[SKIN]cube_blue.gif",title:"Creating DataSources"},
                                    {id:"38", ref:"group:sqlDataSource", icon:"[SKIN]cube_blue.gif", 
                                     title:"SQL DataSources"},
                                    {id:"39", ref:"group:adminConsole", icon:"[SKIN]cube_blue.gif", 
                                     title:"Admin Console"},
                                    {id:"40", ref:"group:clientOnlyDataSources", 
                                     icon:"[SKIN]cube_blue.gif",title:"Client Only DataSources"},
                                    {id:"141", ref:"class:DataSourceField", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"DataSourceField"},
                                    {id:"142", ref:"object:SerializationContext", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"SerializationContext"},
                                    {id:"146", ref:"class:OperationBinding", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"OperationBinding"},
                                    {id:"256", ref:"type:DSCallback", icon:"[SKIN]text_code.gif", 
                                     title:"DSCallback"}
                                ]
                            },
                            {id:"42", ref:"group:clientDataIntegration", icon:"[SKIN]cube_blue.gif", 
                             title:"Client-side Data Integration"},
                            {id:"51", ref:"group:wsdlBinding", icon:"[SKIN]cube_blue.gif", 
                             title:"WSDL Binding"},
                            {id:"54", ref:"group:operations", icon:"[SKIN]cube_blue.gif", 
                             title:"Operations Overview"},
                            {id:"55", ref:"group:dataSourceOperations", icon:"[SKIN]cube_blue.gif", 
                             title:"DataSource Operations"},
                            {id:"57", ref:"group:metadataImport", icon:"[SKIN]cube_blue.gif", 
                             title:"Metadata Import"},
                            {id:"59", ref:"group:treeDataBinding", icon:"[SKIN]cube_blue.gif", 
                             title:"Tree DataBinding"},
                            {id:"65", ref:"group:dataBoundComponentMethods", 
                             icon:"[SKIN]cube_blue.gif",title:"DataBound Component Methods"},
                            {id:"140", ref:"class:XMLTools", icon:"[SKIN]text_code_javascript.gif", 
                             title:"XMLTools"},
                            {id:"143", ref:"class:DSResponse", icon:"[SKIN]text_code_javascript.gif", 
                             title:"DSResponse"},
                            {id:"144", ref:"class:DSRequest", icon:"[SKIN]text_code_javascript.gif", 
                             title:"DSRequest"},
                            {id:"147", ref:"class:XJSONDataSource", 
                             icon:"[SKIN]text_code_javascript.gif",title:"XJSONDataSource"},
                            {id:"148", ref:"class:WebService", icon:"[SKIN]text_code_javascript.gif", 
                             title:"WebService"},
                            {id:"149", ref:"class:SchemaSet", icon:"[SKIN]text_code_javascript.gif", 
                             title:"SchemaSet"},
                            {id:"150", ref:"class:WSRequest", icon:"[SKIN]text_code_javascript.gif", 
                             title:"WSRequest"},
                            {id:"155", ref:"class:ResultSet", icon:"[SKIN]text_code_javascript.gif", 
                             title:"ResultSet"},
                            {id:"156", ref:"class:ResultTree", icon:"[SKIN]text_code_javascript.gif", 
                             title:"ResultTree"},
                            {id:"161", ref:"class:WSDataSource", icon:"[SKIN]text_code_javascript.gif", 
                             title:"WSDataSource"},
                            {id:"162", ref:"class:RestDataSource", 
                             icon:"[SKIN]text_code_javascript.gif",title:"RestDataSource"},
                            {id:"198", ref:"class:SimpleType", icon:"[SKIN]text_code_javascript.gif", 
                             title:"SimpleType"},
                            {id:"214", ref:"interface:DataBoundComponent", 
                             icon:"[SKIN]text_code_javascript.gif",title:"DataBoundComponent"},
                            {id:"261", ref:"type:Criteria", icon:"[SKIN]text_code.gif", 
                             title:"Criteria"}
                        ]
                    },
                    {
                        title:"RPC",
                        isFolder:true,
                        id:"19",
                        children:[
                            {id:"53", ref:"group:relogin", icon:"[SKIN]cube_blue.gif", title:"Relogin"},
                            {id:"145", ref:"class:ServerObject", icon:"[SKIN]text_code_javascript.gif", 
                             title:"ServerObject"},
                            {id:"151", ref:"class:RPCManager", icon:"[SKIN]text_code_javascript.gif", 
                             title:"RPCManager"},
                            {id:"152", ref:"class:RPCRequest", icon:"[SKIN]text_code_javascript.gif", 
                             title:"RPCRequest"},
                            {id:"153", ref:"class:RPCResponse", icon:"[SKIN]text_code_javascript.gif", 
                             title:"RPCResponse"},
                            {id:"154", ref:"class:DMI", icon:"[SKIN]text_code_javascript.gif", 
                             title:"DMI"},
                            {id:"258", ref:"type:RPCCallback", icon:"[SKIN]text_code.gif", 
                             title:"RPCCallback"}
                        ]
                    },
                    {
                        title:"System",
                        isFolder:true,
                        id:"20",
                        children:[
                            {id:"52", ref:"group:platformDependencies", icon:"[SKIN]cube_blue.gif", 
                             title:"Platform Dependencies"},
                            {id:"63", ref:"group:stringMethods", icon:"[SKIN]cube_blue.gif", 
                             title:"String Methods Overview"},
                            {id:"67", ref:"interface:List", icon:"[SKIN]text_code_javascript.gif", 
                             title:"List"},
                            {
                                id:"68",
                                ref:"class:Tree",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Tree",
                                children:[
                                    {id:"71", ref:"object:TreeNode", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"TreeNode"}
                                ]
                            },
                            {
                                id:"72",
                                ref:"class:Selection",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Selection",
                                children:[
                                    {id:"87", ref:"class:CellSelection", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"CellSelection"}
                                ]
                            },
                            {id:"137", ref:"class:isc", icon:"[SKIN]text_code_javascript.gif", 
                             title:"isc"},
                            {id:"139", ref:"class:History", icon:"[SKIN]text_code_javascript.gif", 
                             title:"History"},
                            {id:"200", ref:"object:isA", icon:"[SKIN]text_code_javascript.gif", 
                             title:"isA"},
                            {id:"201", ref:"object:ClassFactory", 
                             icon:"[SKIN]text_code_javascript.gif",title:"ClassFactory"},
                            {id:"202", ref:"class:Class", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Class"},
                            {id:"203", ref:"object:Array", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Array"},
                            {id:"204", ref:"object:Number", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Number"},
                            {id:"205", ref:"class:Date", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Date"},
                            {id:"206", ref:"class:String", icon:"[SKIN]text_code_javascript.gif", 
                             title:"String"},
                            {id:"207", ref:"class:Log", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Log"},
                            {id:"208", ref:"class:Time", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Time"},
                            {id:"209", ref:"class:Page", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Page"},
                            {id:"210", ref:"class:Timer", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Timer"},
                            {id:"211", ref:"class:EventHandler", icon:"[SKIN]text_code_javascript.gif", 
                             title:"EventHandler"},
                            {
                                id:"223",
                                title:"Types",
                                children:[
                                    {id:"224", ref:"type:DisplayNodeType", icon:"[SKIN]text_code.gif", 
                                     title:"DisplayNodeType"},
                                    {id:"225", ref:"type:TreeModelType", icon:"[SKIN]text_code.gif", 
                                     title:"TreeModelType"},
                                    {id:"226", ref:"type:SelectionStyle", icon:"[SKIN]text_code.gif", 
                                     title:"SelectionStyle"},
                                    {id:"227", ref:"type:SortArrow", icon:"[SKIN]text_code.gif", 
                                     title:"SortArrow"},
                                    {id:"228", ref:"type:DragDataAction", icon:"[SKIN]text_code.gif", 
                                     title:"DragDataAction"},
                                    {id:"229", ref:"type:RowEndEditAction", icon:"[SKIN]text_code.gif", 
                                     title:"RowEndEditAction"},
                                    {id:"230", ref:"type:EnterKeyEditAction", 
                                     icon:"[SKIN]text_code.gif",title:"EnterKeyEditAction"},
                                    {id:"231", ref:"type:EscapeKeyEditAction", 
                                     icon:"[SKIN]text_code.gif",title:"EscapeKeyEditAction"},
                                    {id:"232", ref:"type:EditCompletionEvent", 
                                     icon:"[SKIN]text_code.gif",title:"EditCompletionEvent"},
                                    {id:"233", ref:"type:ListGridFieldType", 
                                     icon:"[SKIN]text_code.gif",title:"ListGridFieldType"},
                                    {id:"234", ref:"type:ListGridEditEvent", 
                                     icon:"[SKIN]text_code.gif",title:"ListGridEditEvent"},
                                    {id:"235", ref:"type:DragTrackerMode", icon:"[SKIN]text_code.gif", 
                                     title:"DragTrackerMode"},
                                    {id:"236", ref:"type:listGridFieldState", 
                                     icon:"[SKIN]text_code.gif",title:"listGridFieldState"},
                                    {id:"237", ref:"type:listGridSelectedState", 
                                     icon:"[SKIN]text_code.gif",title:"listGridSelectedState"},
                                    {id:"238", ref:"type:listGridSortState", 
                                     icon:"[SKIN]text_code.gif",title:"listGridSortState"},
                                    {id:"239", ref:"type:listGridViewState", 
                                     icon:"[SKIN]text_code.gif",title:"listGridViewState"},
                                    {id:"240", ref:"type:treeGridOpenState", 
                                     icon:"[SKIN]text_code.gif",title:"treeGridOpenState"},
                                    {id:"241", ref:"type:treeGridViewState", 
                                     icon:"[SKIN]text_code.gif",title:"treeGridViewState"},
                                    {id:"242", ref:"type:MenuFieldID", icon:"[SKIN]text_code.gif", 
                                     title:"MenuFieldID"},
                                    {id:"243", ref:"type:FormMethod", icon:"[SKIN]text_code.gif", 
                                     title:"FormMethod"},
                                    {id:"244", ref:"type:Encoding", icon:"[SKIN]text_code.gif", 
                                     title:"Encoding"},
                                    {id:"245", ref:"type:TitleOrientation", icon:"[SKIN]text_code.gif", 
                                     title:"TitleOrientation"},
                                    {id:"246", ref:"type:FormItemType", icon:"[SKIN]text_code.gif", 
                                     title:"FormItemType"},
                                    {id:"247", ref:"type:FormItemBaseStyle", 
                                     icon:"[SKIN]text_code.gif",title:"FormItemBaseStyle"},
                                    {id:"248", ref:"type:TEXTAREA_WRAP", icon:"[SKIN]text_code.gif", 
                                     title:"TEXTAREA_WRAP"},
                                    {id:"249", ref:"type:ControlName", icon:"[SKIN]text_code.gif", 
                                     title:"ControlName"},
                                    {id:"250", ref:"type:XMLDocument", icon:"[SKIN]text_code.gif", 
                                     title:"XMLDocument"},
                                    {id:"251", ref:"type:XMLElement", icon:"[SKIN]text_code.gif", 
                                     title:"XMLElement"},
                                    {id:"252", ref:"type:DSOperationType", icon:"[SKIN]text_code.gif", 
                                     title:"DSOperationType"},
                                    {id:"253", ref:"type:DSDataFormat", icon:"[SKIN]text_code.gif", 
                                     title:"DSDataFormat"},
                                    {id:"254", ref:"type:DSServerType", icon:"[SKIN]text_code.gif", 
                                     title:"DSServerType"},
                                    {id:"255", ref:"type:FieldType", icon:"[SKIN]text_code.gif", 
                                     title:"FieldType"},
                                    {id:"257", ref:"type:DSProtocol", icon:"[SKIN]text_code.gif", 
                                     title:"DSProtocol"},
                                    {id:"259", ref:"type:RPCTransport", icon:"[SKIN]text_code.gif", 
                                     title:"RPCTransport"},
                                    {id:"260", ref:"type:PromptStyle", icon:"[SKIN]text_code.gif", 
                                     title:"PromptStyle"},
                                    {id:"262", ref:"type:FetchMode", icon:"[SKIN]text_code.gif", 
                                     title:"FetchMode"},
                                    {id:"263", ref:"type:CriteriaPolicy", icon:"[SKIN]text_code.gif", 
                                     title:"CriteriaPolicy"},
                                    {id:"264", ref:"type:FacetValueMap", icon:"[SKIN]text_code.gif", 
                                     title:"FacetValueMap"},
                                    {id:"265", ref:"type:ChartType", icon:"[SKIN]text_code.gif", 
                                     title:"ChartType"},
                                    {id:"266", ref:"type:AnimationAcceleration", 
                                     icon:"[SKIN]text_code.gif",title:"AnimationAcceleration"},
                                    {id:"267", ref:"type:State", icon:"[SKIN]text_code.gif", 
                                     title:"State"},
                                    {id:"268", ref:"type:SelectionType", icon:"[SKIN]text_code.gif", 
                                     title:"SelectionType"},
                                    {id:"269", ref:"type:Selected", icon:"[SKIN]text_code.gif", 
                                     title:"Selected"},
                                    {id:"270", ref:"type:Orientation", icon:"[SKIN]text_code.gif", 
                                     title:"Orientation"},
                                    {id:"271", ref:"type:LayoutPolicy", icon:"[SKIN]text_code.gif", 
                                     title:"LayoutPolicy"},
                                    {id:"272", ref:"type:VisibilityMode", icon:"[SKIN]text_code.gif", 
                                     title:"VisibilityMode"},
                                    {id:"273", ref:"type:Callback", icon:"[SKIN]text_code.gif", 
                                     title:"Callback"},
                                    {id:"274", ref:"type:Properties", icon:"[SKIN]text_code.gif", 
                                     title:"Properties"},
                                    {id:"275", ref:"type:ObjectLiteral", icon:"[SKIN]text_code.gif", 
                                     title:"ObjectLiteral"},
                                    {id:"276", ref:"type:AutoChild", icon:"[SKIN]text_code.gif", 
                                     title:"AutoChild"},
                                    {id:"277", ref:"type:DateInputFormat", icon:"[SKIN]text_code.gif", 
                                     title:"DateInputFormat"},
                                    {id:"278", ref:"type:DateDisplayFormat", 
                                     icon:"[SKIN]text_code.gif",title:"DateDisplayFormat"},
                                    {id:"279", ref:"type:LogPriority", icon:"[SKIN]text_code.gif", 
                                     title:"LogPriority"},
                                    {id:"280", ref:"type:SortDirection", icon:"[SKIN]text_code.gif", 
                                     title:"SortDirection"},
                                    {id:"281", ref:"type:timeFormatter", icon:"[SKIN]text_code.gif", 
                                     title:"timeFormatter"},
                                    {id:"282", ref:"type:SendMethod", icon:"[SKIN]text_code.gif", 
                                     title:"SendMethod"},
                                    {id:"283", ref:"type:FireStyle", icon:"[SKIN]text_code.gif", 
                                     title:"FireStyle"},
                                    {id:"284", ref:"type:PageEvent", icon:"[SKIN]text_code.gif", 
                                     title:"PageEvent"},
                                    {id:"285", ref:"type:DragAppearance", icon:"[SKIN]text_code.gif", 
                                     title:"DragAppearance"},
                                    {id:"286", ref:"type:KeyName", icon:"[SKIN]text_code.gif", 
                                     title:"KeyName"},
                                    {id:"287", ref:"type:KeyIdentifier", icon:"[SKIN]text_code.gif", 
                                     title:"KeyIdentifier"},
                                    {id:"288", ref:"type:clickMaskMode", icon:"[SKIN]text_code.gif", 
                                     title:"clickMaskMode"},
                                    {id:"289", ref:"type:Positioning", icon:"[SKIN]text_code.gif", 
                                     title:"Positioning"},
                                    {id:"290", ref:"type:Visibility", icon:"[SKIN]text_code.gif", 
                                     title:"Visibility"},
                                    {id:"291", ref:"type:Overflow", icon:"[SKIN]text_code.gif", 
                                     title:"Overflow"},
                                    {id:"292", ref:"type:Alignment", icon:"[SKIN]text_code.gif", 
                                     title:"Alignment"},
                                    {id:"293", ref:"type:VerticalAlignment", 
                                     icon:"[SKIN]text_code.gif",title:"VerticalAlignment"},
                                    {id:"294", ref:"type:Side", icon:"[SKIN]text_code.gif", 
                                     title:"Side"},
                                    {id:"295", ref:"type:Direction", icon:"[SKIN]text_code.gif", 
                                     title:"Direction"},
                                    {id:"296", ref:"type:Cursor", icon:"[SKIN]text_code.gif", 
                                     title:"Cursor"},
                                    {id:"297", ref:"type:ImageStyle", icon:"[SKIN]text_code.gif", 
                                     title:"ImageStyle"},
                                    {id:"298", ref:"type:DrawPosition", icon:"[SKIN]text_code.gif", 
                                     title:"DrawPosition"},
                                    {id:"299", ref:"type:CSSStyleName", icon:"[SKIN]text_code.gif", 
                                     title:"CSSStyleName"},
                                    {id:"300", ref:"type:PercentBoxModel", icon:"[SKIN]text_code.gif", 
                                     title:"PercentBoxModel"},
                                    {id:"301", ref:"type:SCImgURL", icon:"[SKIN]text_code.gif", 
                                     title:"SCImgURL"},
                                    {id:"302", ref:"type:DialogButtons", icon:"[SKIN]text_code.gif", 
                                     title:"DialogButtons"},
                                    {id:"303", ref:"type:EdgeSizes", icon:"[SKIN]text_code.gif", 
                                     title:"EdgeSizes"}
                                ]
                            }
                        ]
                    },
                    {
                        id:"135",
                        title:"Connectors",
                        children:[
                            {id:"136", ref:"class:EBay", icon:"[SKIN]text_code_javascript.gif", 
                             title:"EBay"}
                        ]
                    }
                ],
                id:"1"
            },
            {
                isOpen:"true",
                requiresModules:"SCServer",
                id:"javaServerReference",
                title:"Java Server Reference",
                children:[
                    {title:"SmartClient Server Summary", id:"21", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:iscServer"},
                    {title:"Server DataSource Integration", id:"22", icon:"[SKIN]cube_blue.gif", 
                     ref:"group:serverDataIntegration"},
                    {contentsURL:"[referenceRoot]server/javadoc/index.html", icon:"[SKIN]cup.gif", 
                     title:"Javadoc",id:"23"},
                    {
                        icon:"[SKIN]cube_blue.gif",
                        isOpen:"true",
                        ref:"group:jspTags",
                        title:"SmartClient JSP Tags",
                        isFolder:true,
                        id:"24",
                        children:[
                            {id:"43", ref:"group:loadISCTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:loadISC&gt;"},
                            {id:"44", ref:"group:loadModulesTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:loadModules&gt;"},
                            {id:"45", ref:"group:loadDSTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:loadDS&gt;"},
                            {id:"46", ref:"group:loadUITag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:loadUI&gt;"},
                            {id:"47", ref:"group:xmlTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:XML&gt;"},
                            {id:"48", ref:"group:loadXMLSchemaTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:loadXMLSchema&gt;"},
                            {id:"49", ref:"group:loadWSDLTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:loadWSDL&gt;"},
                            {id:"50", ref:"group:jsStringTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:jsString&gt;"},
                            {id:"58", ref:"group:loadDMIStubsTag", icon:"[SKIN]cube_blue.gif", 
                             title:"&lt;isomorphic:loadDMIStubs&gt;"}
                        ]
                    }
                ]
            },
            {
                isOpen:"false",
                id:"optionalModules",
                title:"Optional Modules",
                children:[
                    {
                        isOpen:"false",
                        requiresModules:"Analytics",
                        title:"Analytics",
                        isFolder:true,
                        children:[
                            {contentsURL:"[docRoot]resources/Analytics_QuickRef.pdf", 
                             icon:"[SKIN]pdf.gif",title:"CubeGrid QuickRef", id:"29"},
                            {
                                id:"163",
                                ref:"class:CubeGrid",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"CubeGrid",
                                children:[
                                    {id:"164", ref:"class:Facet", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"Facet"},
                                    {id:"165", ref:"class:FacetValue", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"FacetValue"},
                                    {id:"166", ref:"object:GridHilite", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"GridHilite"},
                                    {id:"167", ref:"object:CellRecord", 
                                     icon:"[SKIN]text_code_javascript.gif",title:"CellRecord"}
                                ]
                            },
                            {id:"168", ref:"interface:Chart", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Chart"},
                            {id:"169", ref:"class:FusionChart", icon:"[SKIN]text_code_javascript.gif", 
                             title:"FusionChart"}
                        ],
                        id:"25"
                    },
                    {
                        isOpen:"false",
                        requiresModules:"RealtimeMessaging",
                        title:"Messaging",
                        isFolder:true,
                        children:[
                            {contentsURL:"[docRoot]resources/Messaging_QuickRef.pdf", 
                             icon:"[SKIN]pdf.gif",id:"Messaging QuickRef", 
                             title:"Messaging QuickRef"}
                        ],
                        id:"26"
                    },
                    {
                        isOpen:"false",
                        requiresModules:"PluginBridges",
                        title:"Client Bridges",
                        isFolder:true,
                        id:"27",
                        children:[
                            {id:"130", ref:"class:BrowserPlugin", 
                             icon:"[SKIN]text_code_javascript.gif",title:"BrowserPlugin"},
                            {id:"131", ref:"class:Applet", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Applet"},
                            {id:"132", ref:"class:Flashlet", icon:"[SKIN]text_code_javascript.gif", 
                             title:"Flashlet"},
                            {id:"133", ref:"class:SVG", icon:"[SKIN]text_code_javascript.gif", 
                             title:"SVG"},
                            {id:"134", ref:"class:ActiveXControl", 
                             icon:"[SKIN]text_code_javascript.gif",title:"ActiveXControl"}
                        ]
                    },
                    {
                        isOpen:"false",
                        requiresModules:"NetworkPerformance",
                        title:"Network Performance",
                        isFolder:true,
                        id:"28",
                        icon:"[SKIN]cube_blue.gif",
                        ref:"group:networkPerformance",
                        children:[
                            {id:"60", ref:"group:compression", icon:"[SKIN]cube_blue.gif", 
                             title:"Compression"},
                            {id:"61", ref:"group:caching", icon:"[SKIN]cube_blue.gif", title:"Caching"},
                            {id:"62", ref:"group:fileAssembly", icon:"[SKIN]cube_blue.gif", 
                             title:"File Assembly"},
                            {id:"199", ref:"class:FileLoader", icon:"[SKIN]text_code_javascript.gif", 
                             title:"FileLoader"}
                        ]
                    }
                ]
            }
        ]
    },
    nameProperty:"id",
    showRoot:false,
    openProperty:"isOpen",
    refToID:{"class:DOMGrid":"85", "class:HTMLFlow":"159", "type:RPCTransport":"259", "type:LayoutPolicy":"271", 
     "class:HStack":"174","class:CanvasItem":"95", "object:DetailViewerRecord":"74", 
     "class:FacetValue":"165","class:MenuButton":"84", "group:clientServerIntegration":"2", 
     "type:RPCCallback":"258","class:BrowserPlugin":"130", "class:LinkItem":"108", 
     "class:ToolbarItem":"118","type:SortArrow":"227", "type:DragAppearance":"285", 
     "class:EventHandler":"211","class:HeaderItem":"104", "type:MenuFieldID":"242", 
     "group:upload":"33","class:SectionStack":"189", "class:Page":"209", 
     "type:EnterKeyEditAction":"230","type:treeGridOpenState":"240", "group:loadWSDLTag":"49", 
     "type:FormItemType":"246","type:listGridViewState":"239", "type:SelectionStyle":"226", 
     "class:HTMLPane":"160","type:DSProtocol":"257", "class:DataSourceField":"141", 
     "type:listGridSelectedState":"237","class:RichTextItem":"129", "class:UploadItem":"119", 
     "group:networkPerformance":"28","class:TimeItem":"117", "class:ValuesManager":"127", 
     "class:CubeGrid":"163","class:ViewLoader":"158", "class:SVG":"133", "type:Orientation":"270", 
     "type:State":"267","group:metadataImport":"57", "class:Selection":"72", 
     "type:ListGridEditEvent":"234","group:dataBoundComponentMethods":"65", 
     "type:FacetValueMap":"264","object:SectionStackSection":"190", "class:ImgSplitbar":"195", 
     "class:WebService":"148","group:fileAssembly":"62", "type:AnimationAcceleration":"266", 
     "class:SelectItem":"100","class:DetailViewer":"73", "class:PickTreeItem":"125", 
     "group:operations":"54","class:OperationBinding":"146", "class:Log":"207", 
     "type:FieldType":"255","class:DateChooser":"88", "type:Direction":"295", "type:SCImgURL":"301", 
     "object:CellRecord":"167","class:FormItem":"91", "class:ImgTab":"217", "type:LogPriority":"279", 
     "type:DateInputFormat":"277","class:Layout":"171", "object:DetailViewerField":"75", 
     "type:PromptStyle":"260","type:DialogButtons":"302", "type:PercentBoxModel":"300", 
     "type:VerticalAlignment":"293","class:XJSONDataSource":"147", "class:ImgSectionHeader":"192", 
     "group:sqlDataSource":"38","class:VStack":"175", "class:isc":"137", 
     "group:dataSourceDeclaration":"36","type:Positioning":"289", "type:TEXTAREA_WRAP":"248", 
     "class:StatefulCanvas":"170","type:CriteriaPolicy":"263", "type:ObjectLiteral":"275", 
     "class:RichTextEditor":"128","group:platformDependencies":"52", "type:listGridSortState":"238", 
     "type:DisplayNodeType":"224","class:Tree":"68", "group:loadUITag":"46", 
     "type:treeGridViewState":"241","object:TreeNode":"71", "object:ListGridRecord":"78", 
     "type:DSCallback":"256","type:Cursor":"296", "type:Alignment":"292", "class:ResetItem":"111", 
     "type:Overflow":"291","object:groupNode":"79", "type:PageEvent":"284", "class:DSRequest":"144", 
     "group:dataSourceOperations":"55","class:SpacerItem":"113", "type:DateDisplayFormat":"278", 
     "class:RowSpacerItem":"114","class:ResultSet":"155", "class:SchemaSet":"149", 
     "class:String":"206","type:KeyName":"286", "interface:PickList":"99", "class:ResultTree":"156", 
     "class:Class":"202","class:Validator":"93", "type:DSServerType":"254", "type:FormMethod":"243", 
     "class:Slider":"89","class:SpinnerItem":"123", "interface:List":"67", "object:Number":"204", 
     "type:CSSStyleName":"299","type:XMLElement":"251", "type:Callback":"273", "type:FireStyle":"283", 
     "type:FormItemBaseStyle":"247","group:springIntegration":"8", "class:EdgedCanvas":"215", 
     "type:listGridFieldState":"236","type:XMLDocument":"250", "group:smartArchitecture":"3", 
     "group:loadDMIStubsTag":"58","group:visualBuilder":"6", "class:DSResponse":"143", 
     "type:Selected":"269","group:wsdlBinding":"51", "class:Flashlet":"132", "class:FileItem":"32", 
     "class:NativeCheckboxItem":"103","class:MultiFileItem":"121", "class:PasswordItem":"109", 
     "type:EscapeKeyEditAction":"231","type:Criteria":"261", "class:Img":"180", 
     "class:ComboBoxItem":"120","type:DrawPosition":"298", "class:MenuBar":"86", 
     "class:RadioGroupItem":"110","class:StaticTextItem":"107", "class:SearchForm":"126", 
     "object:ImgProperties":"213","type:ControlName":"249", "class:ActiveXControl":"134", 
     "group:treeDataBinding":"59","group:caching":"61", "group:clientOnlyDataSources":"40", 
     "type:clickMaskMode":"288","type:SortDirection":"280", "class:RPCResponse":"153", 
     "class:SliderItem":"124","group:i18n":"37", "type:Encoding":"244", "class:LayoutSpacer":"176", 
     "class:RPCRequest":"152","group:debugging":"4", "class:Scrollbar":"193", "type:ImageStyle":"297", 
     "object:ListGridField":"80","type:ChartType":"265", "group:hibernateIntegration":"9", 
     "class:Hover":"216","class:Button":"177", "type:AutoChild":"276", "group:iscInstall":"5", 
     "type:VisibilityMode":"272","class:DynamicForm":"90", "class:RestDataSource":"162", 
     "class:ButtonItem":"98","class:Menu":"82", "class:ToolStripResizer":"197", 
     "group:featureExplorerOverview":"featureExplorerOverview","object:isA":"200", 
     "class:EBay":"136","group:xmlTag":"47", "class:Facet":"164", "class:Applet":"131", 
     "class:SectionHeader":"191","class:TabBar":"219", "type:SendMethod":"282", 
     "type:Visibility":"290","object:MenuItem":"83", "type:DragDataAction":"228", 
     "class:Progressbar":"183","type:Side":"294", "group:jsfIntegration":"10", "class:Date":"205", 
     "class:SimpleType":"198","class:MultiFilePicker":"122", "group:nonJavaBackend":"7", 
     "group:strutsIntegration":"11","class:ToolStripSeparator":"186", "group:componentSchema":"34", 
     "group:adminConsole":"39","group:formLayout":"30", "class:ValidatorTypes":"94", 
     "object:GridHilite":"166","type:FetchMode":"262", "class:SectionItem":"105", 
     "class:TextItem":"96","class:RPCManager":"151", "group:clientDataIntegration":"42", 
     "class:SelectOtherItem":"101","group:loadDSTag":"45", "class:TreeGrid":"69", 
     "group:loadModulesTag":"44","type:EdgeSizes":"303", "type:EditCompletionEvent":"232", 
     "object:Tab":"222","group:Prompting":"66", "object:SerializationContext":"142", 
     "object:Browser":"138","class:Timer":"210", "object:Array":"203", "group:loadISCTag":"43", 
     "class:TabSet":"218","object:TreeGridField":"81", "object:FormItemIcon":"92", 
     "class:HiddenItem":"106","class:ImgButton":"187", "class:DMI":"154", "group:skinning":"64", 
     "class:XMLTools":"140","type:TreeModelType":"225", "class:StretchImgButton":"188", 
     "class:ToolStrip":"185","class:DateItem":"112", "class:DataSource":"35", "interface:Chart":"168", 
     "type:DSOperationType":"252","group:loadXMLSchemaTag":"48", "group:serverDataIntegration":"22", 
     "class:FileLoader":"199","type:SelectionType":"268", "class:Window":"220", "class:ListGrid":"77", 
     "group:compression":"60","type:Properties":"274", "class:History":"139", 
     "type:DragTrackerMode":"235","type:TitleOrientation":"245", "class:Time":"208", 
     "type:KeyIdentifier":"287","class:AutoFitButton":"178", "class:BlurbItem":"97", 
     "type:RowEndEditAction":"229","type:timeFormatter":"281", "class:Toolbar":"184", 
     "class:SubmitItem":"115","interface:DataBoundComponent":"214", "class:ServerObject":"145", 
     "group:jsStringTag":"50","class:Dialog":"221", "class:CheckboxItem":"102", "class:Label":"182", 
     "type:DSDataFormat":"253","class:GridRenderer":"76", "object:ClassFactory":"201", 
     "class:WSRequest":"150","class:CellSelection":"87", "group:iscServer":"21", 
     "group:componentXML":"12","group:jspTags":"24", "class:StretchImg":"181", 
     "type:ListGridFieldType":"233","class:Canvas":"212", "class:Splitbar":"194", 
     "class:PropertySheet":"157","class:FusionChart":"169", "class:VLayout":"173", 
     "group:relogin":"53","group:stringMethods":"63", "class:IButton":"179", 
     "class:WSDataSource":"161","class:Snapbar":"196", "class:HLayout":"172", 
     "class:TextAreaItem":"116"}
})
