<?php
header("Expires: 0");
require_once("../../Includes/Connection.php");
require_once("../../Includes/Constantes.php"); 
require_once("../../Includes/mantenimiento.php");
require_once("../includes/clsCA_Turnos_Empleado.php");
require_once("../../Includes/fpdf153/fpdf.php");

$tc_codigo_sap="";
$tipo_area_codigo="1";
$turno_hora_inicio="-1";
$turno_minuto_inicio="-1";
$turno_horas="0";
$turno_minutos="0";
$tc_activo="0";
$empleado_id="";
$te_semana="";
$te_anio="";
$tc_codigo="";
$empleado_nombre="";
$empleado_rut="";
$empleado_login="";
$pdf_codigo=date("YmdHis");

$cturno_dia1="0";$tturno_dia1="";$fturno_dia1="";
$cturno_dia2="0";$tturno_dia2="";$fturno_dia2="";
$cturno_dia3="0";$tturno_dia3="";$fturno_dia3="";
$cturno_dia4="0";$tturno_dia4="";$fturno_dia4="";
$cturno_dia5="0";$tturno_dia5="";$fturno_dia5="";
$cturno_dia6="0";$tturno_dia6="";$fturno_dia6="";
$cturno_dia7="0";$tturno_dia7="";$fturno_dia7="";
$lturno_dia1="";$dturno_dia1="";$nturno_dia1="";
$lturno_dia2="";$dturno_dia2="";$nturno_dia2="";
$lturno_dia3="";$dturno_dia3="";$nturno_dia3="";
$lturno_dia4="";$dturno_dia4="";$nturno_dia4="";
$lturno_dia5="";$dturno_dia5="";$nturno_dia5="";
$lturno_dia6="";$dturno_dia6="";$nturno_dia6="";
$lturno_dia7="";$dturno_dia7="";$nturno_dia7="";
$total_horas="";$total_minutos="";
$eturno_dia1="0";$sturno_dia1="";$tferiado1="";
$eturno_dia2="0";$sturno_dia2="";$tferiado2="";
$eturno_dia3="0";$sturno_dia3="";$tferiado3="";
$eturno_dia4="0";$sturno_dia4="";$tferiado4="";
$eturno_dia5="0";$sturno_dia5="";$tferiado5="";
$eturno_dia6="0";$sturno_dia6="";$tferiado6="";
$eturno_dia7="0";$sturno_dia7="";$tferiado7="";
$horas_refrigerio="";$minutos_refrigerio="";
$te_fecha_inicio="";$te_fecha_fin="";

$xcturno_dia1="0";$xtturno_dia1="";$xfturno_dia1="";
$xcturno_dia2="0";$xtturno_dia2="";$xfturno_dia2="";
$xcturno_dia3="0";$xtturno_dia3="";$xfturno_dia3="";
$xcturno_dia4="0";$xtturno_dia4="";$xfturno_dia4="";
$xcturno_dia5="0";$xtturno_dia5="";$xfturno_dia5="";
$xcturno_dia6="0";$xtturno_dia6="";$xfturno_dia6="";
$xcturno_dia7="0";$xtturno_dia7="";$xfturno_dia7="";
$xlturno_dia1="";$xdturno_dia1="";$xnturno_dia1="";
$xlturno_dia2="";$xdturno_dia2="";$xnturno_dia2="";
$xlturno_dia3="";$xdturno_dia3="";$xnturno_dia3="";
$xlturno_dia4="";$xdturno_dia4="";$xnturno_dia4="";
$xlturno_dia5="";$xdturno_dia5="";$xnturno_dia5="";
$xlturno_dia6="";$xdturno_dia6="";$xnturno_dia6="";
$xlturno_dia7="";$xdturno_dia7="";$xnturno_dia7="";
$xtotal_horas="";$xtotal_minutos="";
$xeturno_dia1="0";$xsturno_dia1="";$xtferiado1="";
$xeturno_dia2="0";$xsturno_dia2="";$xtferiado2="";
$xeturno_dia3="0";$xsturno_dia3="";$xtferiado3="";
$xeturno_dia4="0";$xsturno_dia4="";$xtferiado4="";
$xeturno_dia5="0";$xsturno_dia5="";$xtferiado5="";
$xeturno_dia6="0";$xsturno_dia6="";$xtferiado6="";
$xeturno_dia7="0";$xsturno_dia7="";$xtferiado7="";
$xhoras_refrigerio="";$xminutos_refrigerio="";

//if (isset($_GET["tc_codigo"])) $tc_codigo = $_GET["tc_codigo"];
if (isset($_GET["empleado_id"])) $empleado_id = $_GET["empleado_id"];
if (isset($_GET["te_semana"])) $te_semana = $_GET["te_semana"];
if (isset($_GET["te_anio"])) $te_anio = $_GET["te_anio"];
if (isset($_GET["te_fecha_inicio"])) $te_fecha_inicio = $_GET["te_fecha_inicio"];
if (isset($_GET["te_fecha_fin"])) $te_fecha_fin = $_GET["te_fecha_fin"];
//if (isset($_GET["empleado_nombre"])) $empleado_nombre = $_GET["empleado_nombre"];


$e = new ca_turnos_empleado();
$e->MyUrl = db_host();
$e->MyUser= db_user();
$e->MyPwd = db_pass();
$e->MyDBName= db_name();

if ($te_semana!="" && $te_anio!="" && $empleado_id!=""){

	$e->empleado_codigo = $empleado_id;
	$mensaje = $e->Query_Empleado_Nombres();
	$empleado_nombre = $e->empleado_nombres;
	$empleado_rut = $e->empleado_dni;
	$e->te_semana = $te_semana;
	$e->te_anio = $te_anio;
	$mensaje = $e->Query_Turno_Empleado_Sap();
	$tc_codigo_sap = $e->tc_codigo_sap;
	$cturno_dia1 = $e->turno_Dia1;
	$cturno_dia2 = $e->turno_Dia2;
	$cturno_dia3 = $e->turno_Dia3;
	$cturno_dia4 = $e->turno_Dia4;
	$cturno_dia5 = $e->turno_Dia5;
	$cturno_dia6 = $e->turno_Dia6;
	$cturno_dia7 = $e->turno_Dia7;
	$tc_activo = $e->tc_activo;
	$tturno_dia1 = $e->tturno_Dia1;
	$tturno_dia2 = $e->tturno_Dia2;
	$tturno_dia3 = $e->tturno_Dia3;
	$tturno_dia4 = $e->tturno_Dia4;
	$tturno_dia5 = $e->tturno_Dia5;
	$tturno_dia6 = $e->tturno_Dia6;
	$tturno_dia7 = $e->tturno_Dia7;
	$lturno_dia1 = $e->lturno_Dia1;
	$lturno_dia2 = $e->lturno_Dia2;
	$lturno_dia3 = $e->lturno_Dia3;
	$lturno_dia4 = $e->lturno_Dia4;
	$lturno_dia5 = $e->lturno_Dia5;
	$lturno_dia6 = $e->lturno_Dia6;
	$lturno_dia7 = $e->lturno_Dia7;
	$dturno_dia1 = $e->dturno_Dia1;
	$dturno_dia2 = $e->dturno_Dia2;
	$dturno_dia3 = $e->dturno_Dia3;
	$dturno_dia4 = $e->dturno_Dia4;
	$dturno_dia5 = $e->dturno_Dia5;
	$dturno_dia6 = $e->dturno_Dia6;
	$dturno_dia7 = $e->dturno_Dia7;
	$nturno_dia1 = $e->nturno_Dia1;
	$nturno_dia2 = $e->nturno_Dia2;
	$nturno_dia3 = $e->nturno_Dia3;
	$nturno_dia4 = $e->nturno_Dia4;
	$nturno_dia5 = $e->nturno_Dia5;
	$nturno_dia6 = $e->nturno_Dia6;
	$nturno_dia7 = $e->nturno_Dia7;
	$total_horas = $e->total_horas;
	$total_minutos = $e->total_minutos;
	$eturno_dia1 = $e->eturno_Dia1;
	$eturno_dia2 = $e->eturno_Dia2;
	$eturno_dia3 = $e->eturno_Dia3;
	$eturno_dia4 = $e->eturno_Dia4;
	$eturno_dia5 = $e->eturno_Dia5;
	$eturno_dia6 = $e->eturno_Dia6;
	$eturno_dia7 = $e->eturno_Dia7;
	$sturno_dia1 = $e->sturno_Dia1;
	$sturno_dia2 = $e->sturno_Dia2;
	$sturno_dia3 = $e->sturno_Dia3;
	$sturno_dia4 = $e->sturno_Dia4;
	$sturno_dia5 = $e->sturno_Dia5;
	$sturno_dia6 = $e->sturno_Dia6;
	$sturno_dia7 = $e->sturno_Dia7;
	$horas_refrigerio = $e->horas_refrigerio;
	$minutos_refrigerio = $e->minutos_refrigerio;
	$fturno_dia1 = $e->fturno_Dia1;
	$fturno_dia2 = $e->fturno_Dia2;
	$fturno_dia3 = $e->fturno_Dia3;
	$fturno_dia4 = $e->fturno_Dia4;
	$fturno_dia5 = $e->fturno_Dia5;
	$fturno_dia6 = $e->fturno_Dia6;
	$fturno_dia7 = $e->fturno_Dia7;
	$tmp_inicio = split("/",$te_fecha_inicio);
	$tmp_fin = split("/",$te_fecha_fin);
	$e->te_fecha_inicio = $tmp_inicio[2] . $tmp_inicio[1] . $tmp_inicio[0];
	$e->te_fecha_fin = $tmp_fin[2] . $tmp_fin[1] . $tmp_fin[0];
	$e->Query_Turno_Feriados();
	$tferiado1 = $e->tferiado1;
	$tferiado2 = $e->tferiado2;
	$tferiado3 = $e->tferiado3;
	$tferiado4 = $e->tferiado4;
	$tferiado5 = $e->tferiado5;
	$tferiado6 = $e->tferiado6;
	$tferiado7 = $e->tferiado7;

	$mensaje = $e->Query_Turno_Empleado_Sap('C');
	$xtc_codigo_sap = $e->tc_codigo_sap;
	$xcturno_dia1 = $e->turno_Dia1;
	$xcturno_dia2 = $e->turno_Dia2;
	$xcturno_dia3 = $e->turno_Dia3;
	$xcturno_dia4 = $e->turno_Dia4;
	$xcturno_dia5 = $e->turno_Dia5;
	$xcturno_dia6 = $e->turno_Dia6;
	$xcturno_dia7 = $e->turno_Dia7;
	$xtc_activo = $e->tc_activo;
	$xtturno_dia1 = $e->tturno_Dia1;
	$xtturno_dia2 = $e->tturno_Dia2;
	$xtturno_dia3 = $e->tturno_Dia3;
	$xtturno_dia4 = $e->tturno_Dia4;
	$xtturno_dia5 = $e->tturno_Dia5;
	$xtturno_dia6 = $e->tturno_Dia6;
	$xtturno_dia7 = $e->tturno_Dia7;
	$xlturno_dia1 = $e->lturno_Dia1;
	$xlturno_dia2 = $e->lturno_Dia2;
	$xlturno_dia3 = $e->lturno_Dia3;
	$xlturno_dia4 = $e->lturno_Dia4;
	$xlturno_dia5 = $e->lturno_Dia5;
	$xlturno_dia6 = $e->lturno_Dia6;
	$xlturno_dia7 = $e->lturno_Dia7;
	$xdturno_dia1 = $e->dturno_Dia1;
	$xdturno_dia2 = $e->dturno_Dia2;
	$xdturno_dia3 = $e->dturno_Dia3;
	$xdturno_dia4 = $e->dturno_Dia4;
	$xdturno_dia5 = $e->dturno_Dia5;
	$xdturno_dia6 = $e->dturno_Dia6;
	$xdturno_dia7 = $e->dturno_Dia7;
	$xnturno_dia1 = $e->nturno_Dia1;
	$xnturno_dia2 = $e->nturno_Dia2;
	$xnturno_dia3 = $e->nturno_Dia3;
	$xnturno_dia4 = $e->nturno_Dia4;
	$xnturno_dia5 = $e->nturno_Dia5;
	$xnturno_dia6 = $e->nturno_Dia6;
	$xnturno_dia7 = $e->nturno_Dia7;
	$xtotal_horas = $e->total_horas;
	$xtotal_minutos = $e->total_minutos;
	$xeturno_dia1 = $e->eturno_Dia1;
	$xeturno_dia2 = $e->eturno_Dia2;
	$xeturno_dia3 = $e->eturno_Dia3;
	$xeturno_dia4 = $e->eturno_Dia4;
	$xeturno_dia5 = $e->eturno_Dia5;
	$xeturno_dia6 = $e->eturno_Dia6;
	$xeturno_dia7 = $e->eturno_Dia7;
	$xsturno_dia1 = $e->sturno_Dia1;
	$xsturno_dia2 = $e->sturno_Dia2;
	$xsturno_dia3 = $e->sturno_Dia3;
	$xsturno_dia4 = $e->sturno_Dia4;
	$xsturno_dia5 = $e->sturno_Dia5;
	$xsturno_dia6 = $e->sturno_Dia6;
	$xsturno_dia7 = $e->sturno_Dia7;
	$xhoras_refrigerio = $e->horas_refrigerio;
	$xminutos_refrigerio = $e->minutos_refrigerio;
	$xfturno_dia1 = $e->fturno_Dia1;
	$xfturno_dia2 = $e->fturno_Dia2;
	$xfturno_dia3 = $e->fturno_Dia3;
	$xfturno_dia4 = $e->fturno_Dia4;
	$xfturno_dia5 = $e->fturno_Dia5;
	$xfturno_dia6 = $e->fturno_Dia6;
	$xfturno_dia7 = $e->fturno_Dia7;
	
}

$pdf = new FPDF();

$pdf->SetFont('courier','',9);
$pdf->SetTopMargin(20);
$pdf->AddPage();
$pdf->Image('../../images/atento.jpg',165,20,33);
$pdf->Cell(200,6,'SOLICITUD DE CAMBIO DE SUPLENCIA PROVISORIA',0,1,'C');
$pdf->Ln();
$pdf->Cell(200,5,'YO ....................................................DNI ....................',0,1,'L');
$pdf->Cell(200,5,'Solicito modificar mi turno actual, para el (o los) dia(s)',0,1,'L');
$pdf->Cell(200,5,'...............................................................................',0,1,'L');
$pdf->Cell(200,5,'...............................................................................',0,1,'L');
$pdf->Cell(200,5,'.......... de ................. de .......',0,1,'L');
$pdf->Ln();
$pdf->Cell(200,5,'Nombre del Servicio                       ______________________________________',0,1,'L');
$pdf->Cell(200,5,'Responsable o Solicitante                 ______________________________________',0,1,'L');
$pdf->Ln();
$pdf->Cell(200,5,'TURNO ORIGINAL',0,1,'L');
$pdf->SetFont('courier','',8);
$pdf->Cell(16,4,'DNI',1,0,'C');
$pdf->Cell(71,4,'NOMBRES',1,0,'C');
$pdf->Cell(20,4,'FECHA',1,0,'C');
$pdf->Cell(20,4,'DIA',1,0,'C');
$pdf->Cell(12,4,'INIC',1,0,'C');
$pdf->Cell(12,4,'TERM',1,0,'C');
$pdf->Cell(12,4,'DURAC',1,0,'C');
$pdf->Cell(12,4,'DUR.RE',1,0,'C');
$pdf->Cell(12,4,'DURAC',1,1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$fturno_dia1,'LR',0,'C');
$pdf->Cell(20,4,'Lunes','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia1!='Descanso'?substr($tturno_dia1,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia1!='Descanso'?substr($tturno_dia1,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia1!='Descanso'?(( (substr($nturno_dia1,0,2)*1).'.'.substr($nturno_dia1,3,5)*100/60 )*60-$lturno_dia1)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia1!='Descanso'?$lturno_dia1:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia1!='Descanso'?$total_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$fturno_dia2,'LR',0,'C');
$pdf->Cell(20,4,'Martes','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia2!='Descanso'?substr($tturno_dia2,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia2!='Descanso'?substr($tturno_dia2,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia2!='Descanso'?(( (substr($nturno_dia2,0,2)*1).'.'.substr($nturno_dia2,3,5)*100/60 )*60-$lturno_dia2)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia2!='Descanso'?$lturno_dia2:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia2!='Descanso'?$total_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$fturno_dia3,'LR',0,'C');
$pdf->Cell(20,4,'Miercoles','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia3!='Descanso'?substr($tturno_dia3,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia3!='Descanso'?substr($tturno_dia3,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia3!='Descanso'?(( (substr($nturno_dia3,0,2)*1).'.'.substr($nturno_dia3,3,5)*100/60 )*60-$lturno_dia3)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia3!='Descanso'?$lturno_dia3:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia3!='Descanso'?$total_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$fturno_dia4,'LR',0,'C');
$pdf->Cell(20,4,'Jueves','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia4!='Descanso'?substr($tturno_dia4,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia4!='Descanso'?substr($tturno_dia4,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia4!='Descanso'?(( (substr($nturno_dia4,0,2)*1).'.'.substr($nturno_dia4,3,5)*100/60 )*60-$lturno_dia4)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia4!='Descanso'?$lturno_dia4:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia4!='Descanso'?$total_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$fturno_dia5,'LR',0,'C');
$pdf->Cell(20,4,'Viernes','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia5!='Descanso'?substr($tturno_dia5,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia5!='Descanso'?substr($tturno_dia5,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia5!='Descanso'?(( (substr($nturno_dia5,0,2)*1).'.'.substr($nturno_dia5,3,5)*100/60 )*60-$lturno_dia5)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia5!='Descanso'?$lturno_dia5:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia5!='Descanso'?$total_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$fturno_dia6,'LR',0,'C');
$pdf->Cell(20,4,'Sabado','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia6!='Descanso'?substr($tturno_dia6,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia6!='Descanso'?substr($tturno_dia6,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia6!='Descanso'?(( (substr($nturno_dia6,0,2)*1).'.'.substr($nturno_dia6,3,5)*100/60 )*60-$lturno_dia6)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia6!='Descanso'?$lturno_dia6:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia6!='Descanso'?$total_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$fturno_dia7,'LR',0,'C');
$pdf->Cell(20,4,'Domingo','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia7!='Descanso'?substr($tturno_dia7,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia7!='Descanso'?substr($tturno_dia7,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia7!='Descanso'?(( (substr($nturno_dia7,0,2)*1).'.'.substr($nturno_dia7,3,5)*100/60 )*60-$lturno_dia7)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia7!='Descanso'?$lturno_dia7:'Libre','LR',0,'C');
$pdf->Cell(12,4,$tturno_dia7!='Descanso'?$total_horas:'Libre','LR',1,'C');

$pdf->Cell(187,0,'','T');

$pdf->Ln();
$pdf->SetFont('courier','',9);
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,'TURNO NUEVO',0,1,'L');
$pdf->SetFont('courier','',8);
$pdf->Cell(16,4,'DNI',1,0,'C');
$pdf->Cell(71,4,'NOMBRES',1,0,'C');
$pdf->Cell(20,4,'FECHA',1,0,'C');
$pdf->Cell(20,4,'DIA',1,0,'C');
$pdf->Cell(12,4,'INIC',1,0,'C');
$pdf->Cell(12,4,'TERM',1,0,'C');
$pdf->Cell(12,4,'DURAC',1,0,'C');
$pdf->Cell(12,4,'DUR.RE',1,0,'C');
$pdf->Cell(12,4,'DURAC',1,1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$xfturno_dia1,'LR',0,'C');
$pdf->Cell(20,4,'Lunes','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia1!='Descanso'?substr($xtturno_dia1,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia1!='Descanso'?substr($xtturno_dia1,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia1!='Descanso'?(( (substr($xnturno_dia1,0,2)*1).'.'.substr($xnturno_dia1,3,5)*100/60 )*60-$xlturno_dia1)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia1!='Descanso'?$xlturno_dia1:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia1!='Descanso'?$xtotal_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$xfturno_dia2,'LR',0,'C');
$pdf->Cell(20,4,'Martes','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia2!='Descanso'?substr($xtturno_dia2,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia2!='Descanso'?substr($xtturno_dia2,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia2!='Descanso'?(( (substr($xnturno_dia2,0,2)*1).'.'.substr($xnturno_dia2,3,5)*100/60 )*60-$xlturno_dia2)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia2!='Descanso'?$xlturno_dia2:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia2!='Descanso'?$xtotal_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$xfturno_dia3,'LR',0,'C');
$pdf->Cell(20,4,'Miercoles','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia3!='Descanso'?substr($xtturno_dia3,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia3!='Descanso'?substr($xtturno_dia3,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia3!='Descanso'?(( (substr($xnturno_dia3,0,2)*1).'.'.substr($xnturno_dia3,3,5)*100/60 )*60-$xlturno_dia3)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia3!='Descanso'?$xlturno_dia3:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia3!='Descanso'?$xtotal_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$xfturno_dia4,'LR',0,'C');
$pdf->Cell(20,4,'Jueves','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia4!='Descanso'?substr($xtturno_dia4,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia4!='Descanso'?substr($xtturno_dia4,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia4!='Descanso'?(( (substr($xnturno_dia4,0,2)*1).'.'.substr($xnturno_dia4,3,5)*100/60 )*60-$xlturno_dia4)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia4!='Descanso'?$xlturno_dia4:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia4!='Descanso'?$xtotal_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$xfturno_dia5,'LR',0,'C');
$pdf->Cell(20,4,'Viernes','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia5!='Descanso'?substr($xtturno_dia5,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia5!='Descanso'?substr($xtturno_dia5,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia5!='Descanso'?(( (substr($xnturno_dia5,0,2)*1).'.'.substr($xnturno_dia5,3,5)*100/60 )*60-$xlturno_dia5)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia5!='Descanso'?$xlturno_dia5:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia5!='Descanso'?$xtotal_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$xfturno_dia6,'LR',0,'C');
$pdf->Cell(20,4,'Sabado','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia6!='Descanso'?substr($xtturno_dia6,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia6!='Descanso'?substr($xtturno_dia6,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia6!='Descanso'?(( (substr($xnturno_dia6,0,2)*1).'.'.substr($xnturno_dia6,3,5)*100/60 )*60-$xlturno_dia6)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia6!='Descanso'?$xlturno_dia6:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia6!='Descanso'?$xtotal_horas:'Libre','LR',1,'C');

$pdf->Cell(16,4,$empleado_rut,'LR',0,'C');
$pdf->Cell(71,4,$empleado_nombre,'LR',0,'C');
$pdf->Cell(20,4,$xfturno_dia7,'LR',0,'C');
$pdf->Cell(20,4,'Domingo','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia7!='Descanso'?substr($xtturno_dia7,3,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia7!='Descanso'?substr($xtturno_dia7,11,5):'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia7!='Descanso'?(( (substr($xnturno_dia7,0,2)*1).'.'.substr($xnturno_dia7,3,5)*100/60 )*60-$xlturno_dia7)/60:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia7!='Descanso'?$xlturno_dia7:'Libre','LR',0,'C');
$pdf->Cell(12,4,$xtturno_dia7!='Descanso'?$xtotal_horas:'Libre','LR',1,'C');

$pdf->Cell(187,0,'','T');
$pdf->Ln();
$pdf->SetFont('courier','',9);
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,'Atentamente ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(92,5,'__________________________________',0,0,'C');
$pdf->Cell(92,5,'__________________________________',0,1,'C');
$pdf->Cell(92,5,'FIRMA TELEOPERADOR',0,0,'C');
$pdf->Cell(92,5,'FIRMA COORDINADOR SERVICIO',0,1,'C');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(92,5,'__________________________________',0,0,'C');
$pdf->Cell(92,5,'__________________________________',0,1,'C');
$pdf->Cell(92,5,'NOMBRE TELEOPERADOR',0,0,'C');
$pdf->Cell(92,5,'NOMBRE COORDINADOR SERVICIO',0,1,'C');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,' ',0,1,'L');
$pdf->Cell(200,5,'Lima, ...... de ..................... de 20....',0,0,'L');

$pdf->Output("../reportes_generados/".$pdf_codigo.".pdf");
?>
<script language="javascript">
	//self.location.href="tmp.pdf";
	self.location.href="../reportes_generados/"+<?php echo $pdf_codigo?>+".pdf";
</script>